### ISSUE TITLE
Use PGP for authentication and identification

### ISSUE THREAD

**Issue by willemml** [wicrs/server#19]
Possibly use GPG keys for auth, need to figure out how this would be implemented...

**Comment by x4e** [comment]
Heres what I've been thinking about for a while:

Without authentication the server can be probed for basic information. 
The returned data should contain stuff like the name of the server, and also the IP address or host name of a trusted key server (could potentially be the same server hosting the wicrs instance).
The data should also include the signature of the instance's pgp key which should be present in the provided key server.

### Login/Registration

There is no login process, however there is a sort of registration purpose where the client should retrieve the address of the trusted key server and upload their PGP public key to it.

From then on the user will be known to the wicrs by their key's fingerprint.
All requests to the instance should begin with their fingerprint (as a form of identification) and be signed by the private key corresponding to that fingerprint.
The instance will verify the signature and perform actions in the context of that fingerprint.

### Sending Messages

I will refer to a message not as the text contained in a message, but a full structure including information such as the sender, timestamp and contents.

First the client sends the message to the server (the timestamp is generated clientside on a shared timestamp, perhaps simply use GMT+0).
The sent message will be signed using the user's key (just like all other requests).

The instance will then sign the message and replicate it to other users (including the sender).
This provides every user in the instance a proof that a specific user sent a message at a given time to a given instance, given that they trust either the user or the instance.

Note, this somewhat prevents an instance from censoring messages (any member of the instance at the time it was sent can prove the message's existence), however it does not prevent automated censoring that triggers upon receiving a new message and before replicating it.

### Miscellaneous

Communications between the server and user *could* be encrypted using the user and server pgp keys, however it might be easier just to use TLS.

**Comment by x4e** [comment]
### Identification

To identify the user, clients can use the name field of pgp keys as a display name. 

Because this is arbitrary, people could set their name field in order to impersonate other users.
I therefore propose that clients by default display display names in **red** text.

User's should be able to "trust" pgp keys by adding them to a "known hosts" file, similar to that used by SSH.
Trusted user's should have their name displayed in **green** text.

The email field stored in pgp keys can also be utilised by instances to provide email notifications.

**Comment by willemml** [comment]
Oh wow! Thanks for all the suggestions, very helpful as I don't know much about GPG. I do have a few questions though:
1. Would there be any advantage to encrypting communications between user and server using GPG on top of TLS? Or would it be like that just to allow users to use only GPG auth and then be able to use HTTP as well as HTTPS?
2. So in the sending messages part you said that the timestamp would be generated client side, wouldn't this add issues where the client could send a message "in the past" therefor breaking up conversation or making it look like other people were replying to things that didn't actually exist? Why not just insert the timestamp server-side?
3. Again, in the messages part, why would the server need to notify everyone who is a member of the instance that a message was created? Wouldn't they be able to check at any later time who signed the message?

**Comment by x4e** [comment]
> Would there be any advantage to encrypting communications between user and server using GPG on top of TLS? Or would it be like that just to allow users to use only GPG auth and then be able to use HTTP as well as HTTPS?

No not really, just an idea. I think it would be better to use TLS.
Although this did make me think about the trusted handshake, and I think in order to ensure that the client trusts the server, it should have the same prompt you get with ssh, asking you to verify the servers pgp key fingerprint.

> So in the sending messages part you said that the timestamp would be generated client side, wouldn't this add issues where the client could send a message "in the past" therefor breaking up conversation or making it look like other people were replying to things that didn't actually exist? Why not just insert the timestamp server-side?

Yes it would but the server would simply not sign and not replicate the message if it was beyond a certain threshold which would account for lag. Depending on this threshold however it could potentially be possible for a client to recognise a message like “Who?” and instantly send a message that apparently was sent before that with the contents “Joe”. I’m not sure how this can be combatted.

Also the server can’t be allowed to set the timestamp server side, otherwise they could set a timestamp that is in between two other messages for example in order to incriminate the sender based on that context.
By doing it this way, both the client and server agree on a timestamp that is ok.

> Again, in the messages part, why would the server need to notify everyone who is a member of the instance that a message was created? Wouldn't they be able to check at any later time who signed the message?

It’s just the same as when someone in a discord server sends a message the server sends that message to everyone else in the server. Just means that they can all see it. And yes they would be able to check later, but they would need to download it first.

**Comment by willemml** [comment]
> Although this did make me think about the trusted handshake, and I think in order to ensure that the client trusts the server, it should have the same prompt you get with ssh, asking you to verify the servers PGP key fingerprint.

This actually just made me think, there could be a WebSocket alternative using SSH or something, (user's valid ssh public keys would be stored on the key-server  or something) but it might pose some other problems, I don't know.

> Depending on this threshold however it could potentially be possible for a client to recognise a message like “Who?” and instantly send a message that apparently was sent before that with the contents “Joe”. I’m not sure how this can be combatted.

I guess that the server could also just check the timestamp of the last message, the new message has to have a timestamp after that one (otherwise the server sends a "too early" error response) although maybe also use a threshold or something (two criteria, after the last message and within say 10 seconds (configurable of course) of the servers current time.

> It’s just the same as when someone in a discord server sends a message the server sends that message to everyone else in the server. Just means that they can all see it. And yes they would be able to check later, but they would need to download it first.

Ok so the server doesn't actually have to send the message to anyone, but it should send it to the people who are members of the text channel or, listening for messages they have permission to see.

**Comment by x4e** [comment]
> This actually just made me think, there could be a WebSocket alternative using SSH or something, (user's valid ssh public keys would be stored on the key-server or something) but it might pose some other problems, I don't know.

I think for now websockets and REST APIs are fine, otherwise it could get a bit too complicated lol (and also make creating client implementations hard).

> the server could also just check the timestamp of the last message, the new message has to have a timestamp after that one (otherwise the server sends a "too early" error response)

That could work, but could cause issues if two people try to send a message at the same time, especially if the channel is being spammed or it is just very busy. Whoever had the lower ping could DOS anyone with a higher ping.

One possible solution I thought of for this was checking if the client has sent back a TCP acknowledgement of receiving the last message, however this would require low level packet APIs which could be hard, and could also be bypassed by the client performing similar low level operations (Simply delaying the acknowledgement).

> Ok so the server doesn't actually have to send the message to anyone, but it should send it to the people who are members of the text channel or, listening for messages they have permission to see.

Yeah, everyone currently connected to the channel needs to be sent any messages over the websocket. Could also be other ways it is replicated, for example emailing it to everyone subscribed to a channel.

**Comment by willemml** [comment]
> I think for now websockets and REST APIs are fine, otherwise it could get a bit too complicated lol (and also make creating client implementations hard).

Yeah, I was thinking about it more in a way that the SSH thing would be seperate (like a way to use WICRS over cli, just ssh into the server and then use text commands (kind of like cordless for discord, but over ssh).

> One possible solution I thought of for this was checking if the client has sent back a TCP acknowledgement of receiving the last message, however this would require low level packet APIs which could be hard, and could also be bypassed by the client performing similar low level operations (Simply delaying the acknowledgement).

Actually, what if the client tells the server it wants to send a message, then the server responds with a timestamp and an ID, then the client can send a message with those? It adds quite a bit of overhead, but it could work...


I have been thinking about this, and how does authentication happen for people who don't know how to setup GPG and everything related. The people who just want to do "email, password go!"? And how would you pass your identity around to multiple  devices in a user friendly manner?

**Comment by x4e** [comment]
> Actually, what if the client tells the server it wants to send a message, then the server responds with a timestamp and an ID, then the client can send a message with those? It adds quite a bit of overhead, but it could work...

The client would still be able to change the contents of the message

**Comment by x4e** [comment]
> Actually, what if the client tells the server it wants to send a message, then the server responds with a timestamp and an ID, then the client can send a message with those? It adds quite a bit of overhead, but it could work...

The client would still be able to potentially change the contents of messages.

Another way it could be done is the client sends the text to the server (unsigned), the server responds with a signed packet containing the author, text and timestamp, and the client then signs what the server sent and sends it back.

> I have been thinking about this, and how does authentication happen for people who don't know how to setup GPG and everything related. The people who just want to do "email, password go!"? And how would you pass your identity around to multiple devices in a user friendly manner?

This is more something for clients to deal with than the server, I imagine that clients would let users select a pgp key already existing on their computer, or generate one for them. It could also perhaps allow exporting their pgp key to a text file and importing it for them.

**Comment by willemml** [comment]
I have been thinking, how do users connect from multiple devices? Would it be something like keybase (where you add identities to your account using existing identities (so you would start off with one PGP key on a device, then on the next device you want to add you send a signed user object (which would consist entirely of a user ID, a username and a signed list of PGP keys authorized to access your account), to the server that links your new device's key to your account).

**Comment by x4e** [comment]
You would simply copy your pgp key into that device then you could login as usual. Nothing is required to continue your state other than your pgp private key.

**Comment by willemml** [comment]
I feel like that could make it harder for users who do not know what PGP keys are or don't want to have to deal with sending them to another device, although I guess that a client could do some QR code stuff or similar.

**Comment by x4e** [comment]
Also in the future a possible expansion would be support for master keys, this would let you have a master key that can generate sub keys that can be used to authenticate in wicrs on behalf of the master key. The master key would also be able to revoke keys. This can probably be ignored during the initial implementation though.

**Comment by x4e** [comment]
> I feel like that could make it harder for users who do not know what PGP keys are or don't want to have to deal with sending them to another device, although I guess that a client could do some QR code stuff or similar.

yeah this is more a client than server thing, I’m sure clients can come up with good ways of handling this, with qr codes like you said, or even storing the pgp keys in some cloud or something.

**Comment by willemml** [comment]
Oh yeah, thats a good idea, that probably solves users logging in on other devices... I will probably start working on some sort of implementation for this after I finish GraphQL + WebSockets, although I might actually just rewrite everything from this point, because I am slowly realizing I could optimize the rest of this heavily...

**Comment by x4e** [comment]
Great, really looking forward for this so I can start running my own wicrs instance (and also develop a curses like client hopefully).

**Comment by willemml** [comment]
That would be awesome, and I am also really looking forward to having production ready version (and actual clients, instead of cURL).

**Comment by willemml** [comment]
So I have been exploring existing libraries for PGP in Rust, currently there are a few crates: [`pgp`](https://github.com/rpgp/rpgp), [`sequoia`](https://gitlab.com/sequoia-pgp/sequoia) and [`openpgp`](https://gitlab.com/sequoia-pgp/sequoia/-/tree/main/openpgp) (part of sequoia).

**Comment by willemml** [comment]
Update on the PGP library choice: [`sequoia`](https://gitlab.com/sequoia-pgp/sequoia) and therefore [`openpgp`](https://gitlab.com/sequoia-pgp/sequoia/-/tree/main/openpgp) will not be used because they depend on `nettle` (which means that they are not pure rust) so I am using [`rPGP`](https://github.com/rpgp/rpgp).
