### ISSUE TITLE
[BUG] Invalid http encoding

### ISSUE THREAD

**Issue by x4e** [wicrs/server#26]
At the moment the client sends responses over http in the following format:

```
$ curl -v https://chat.binclub.dev/v3/info
...
< date: Mon, 03 May 2021 14:04:23 GMT
< content-type: application/json
< content-length: 1069
< set-cookie: expires=Wed, 02-Jun-21 14:04:23 GMT; path=/; domain=.binclub.dev; HttpOnly; SameSite=Lax
< alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
<
-----BEGIN PGP MESSAGE-----

yMIkAQHeAiH9xA0DAQgBM8AasnqaCzIBy5d1EXdpY3JzX3NlcnZlcl9pbmZvYI/g
8XsidmVyc2lvbiI6IjAuMTIuMCIsInB1YmxpY19rZXlfZmluZ2VycHJpbnQiOiIz
NjIwNjEyQzI1MzQ5QjQ3N0YxMUNDN0QzM0MwMUFCMjdBOUEwQjMyIiwia2V5X3Nl
cnZlciI6Imh0dHBzOi8va2V5cy5vcGVucGdwLm9yZyJ9wsFzBAEBCAAdFiEENiBh
LCU0m0d/Ecx9M8AasnqaCzIFAmCP4PEACgkQM8AasnqaCzKM2Q/+OHKoVMSXV/Bh
CftVcqawl+lZwK0iyXQDRnvepFAMPPMZA2PDv5rC7EnXpnoqelfUNVjDl1c20OiA
keoImZGgxYb91jRFds895mnI1q6PmWDm4SGYpm/zjGN0/8NokeuPfG4KFSc+87gg
kh3h8b+JLdgvABcyF0c2+qCQ5NgbVCbrhFqJXYNw5tHbvCoYX99tLyrfougwFFYy
siWoGCNhZ0t2S3O5IHx4B6oHpu+7wKftBTeJ3BQpyrLG383w885TRrsPl/F0aBCX
C1k79JIn1Ng/sX21NFUJyt4WXD8pFitxUrJYtQ8R/g38/0zgXy4J8r5jwSy6ppGa
UUWpYjJMDpuMPr+RD+6UfN2jtEf4E8udQoWdZQN46eDM2nomfyOXhm/UOGdiBpZp
3qjlDqwDDDb8Kd8YahMEsWXw4AYi0EuUNJWqupyOVnaWAMKEV/zIAmsm0RLmKu4w
VXYPDAIZII6aPhXj6ZjZtAx5dNZDYcj74xLCnVBO1cD8Iz+xa8Q9gv8rPDyFys4q
5tjFIxC/fjh6K94MOcDehtIf+TiXNVIBhQsphRbB5z2qFZUurVlgW1bysfmi8igt
iMYrce5FtnPewWXU1WNST9Mkc9AxuUDJ6LPNOkvA8IbJ4/F87Uo/pkbA5G7soNNl
tPePYTKUZN/X/OlgA+kDLTf0xz6td2c=
=ovnm
-----END PGP MESSAGE-----
```

The problem is that the returned http body is not `application/json` even though this is the specified mime type.

One solution would be to return this as `text/plain`, which would be a simple hack.

A better solution would be to encode the fact that this is a PGP signature, not just any text. 
According to https://tools.ietf.org/html/rfc3156 the correct way to encode PGP signed data is to include make a multipart response (`multipart/signed`) including the plain text (`text/plain`), and then the signature (`application/pgp-signature`). See section 5.
This would be the best solution, but will require some significant source changes.

Thoughts?

**Comment by x4e** [comment]
I think this would produce the needed signature: https://docs.rs/pgp/0.7.1/pgp/composed/message/enum.Message.html#method.into_signature

**Comment by willemml** [comment]
If multi part signed would be better I don't mind making the changes to the source (I would have done it but for some reason thought it would be better the way it is, I also didn't notice that it was application JSON (too busy fixing other bugs)) nice catch! I will add that to my todo list for tonight

**Comment by x4e** [comment]
I'm happy to implement it myself if you don't have time, shouldn't need much change

**Comment by willemml** [comment]
That would be awesome actually! That way I can spend time working on a client API.

**Comment by x4e** [comment]
Looks like cleartext messages arent actually supported... https://github.com/rpgp/rpgp/blob/26affacc8ad14ce7799a7b5625a98543a3098f25/STATUS.md#L18

**Comment by willemml** [comment]
I guess I should just change it to say `text/plain` then
